version: "3"
services:
  surround:
    image: activityprediction:latest
    command: sh ./docker-entrypoint.sh
    environment:
     - NODE_ENV=${TAG}
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - surroundinstance_volume:/app/instance
    ports:
      - "8080:8080"
    networks:
      - host

volumes:
  surroundinstance_volume:
networks:
   host:
